model_list:
  # Llama 3
  - model_name: llama3:latest
    litellm_params:
      model: ollama/llama3:latest
      api_base: "http://127.0.0.1:11434"
  - model_name: llama3:latest
    litellm_params:
      model: ollama/llama3:latest
      api_base: "http://10.10.0.201:11434"

  # Llama 3.1
  - model_name: llama3.1:latest
    litellm_params:
      model: ollama/llama3.1:latest
      api_base: "http://127.0.0.1:11434"
  - model_name: llama3.1:latest
    litellm_params:
      model: ollama/llama3.1:latest
      api_base: "http://10.10.0.201:11434"

  # Nomic Embed (Local only)
  - model_name: nomic-embed-text:latest
    litellm_params:
      model: ollama/nomic-embed-text:latest
      api_base: "http://127.0.0.1:11434"

  # DeepSeek R1 (Local only)
  - model_name: deepseek-r1:14b
    litellm_params:
      model: ollama/deepseek-r1:14b
      api_base: "http://127.0.0.1:11434"

router_settings:
  routing_strategy: "usage-based-routing-v2"
  num_retries: 2
  timeout: 120
